#pragma once

enum class Event{
    TIME_ADJUST,
    RESET_WIFI,
    ACCEPT,

    POMODORO_CLOCK_SWITCH,
    POMODORO_EXIT,
    POMODORO_START,
    POMODORO_RESET,
    POMODORO_PAUSE,
    POMODORO_SKIP
};